<a href="https://colab.research.google.com/github/hamzaharmanhusni/ProjectSkillAcademyPro/blob/main/FinalProjectSkillAcademy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Project: Portfolio - Final Project

**Instructions for Students:**

Please carefully follow these steps to complete and submit your assignment:

1. **Completing the Assignment**: You are required to work on and complete all tasks in the provided assignment. Be disciplined and ensure that you thoroughly engage with each task.
   
2. **Creating a Google Drive Folder**: If you don't previously have a folder for collecting assignments, you must create a new folder in your Google Drive. This will be a repository for all your completed assignment files, helping you keep your work organized and easy to access.
   
3. **Uploading Completed Assignment**: Upon completion of your assignment, make sure to upload all necessary files, involving codes, reports, and related documents into the created Google Drive folder. Save this link in the 'Student Identity' section and also provide it as the last parameter in the `submit` function that has been provided.
   
4. **Sharing Folder Link**: You're required to share the link to your assignment Google Drive folder. This is crucial for the submission and evaluation of your assignment.
   
5. **Setting Permission toPublic**: Please make sure your **Google Drive folder is set to public**. This allows your instructor to access your solutions and assess your work correctly.

Adhering to these procedures will facilitate a smooth assignment process for you and the reviewers.

**Description:**

Welcome to your final portfolio project assignment for AI Bootcamp. This is your chance to put all the skills and knowledge you've learned throughout the bootcamp into action by creating real-world AI application.

You have the freedom to create any application or model, be it text-based or image-based or even voice-based or multimodal.

To get you started, here are some ideas:

1. **Sentiment Analysis Application:** Develop an application that can determine sentiment (positive, negative, neutral) from text data like reviews or social media posts. You can use Natural Language Processing (NLP) libraries like NLTK or TextBlob, or more advanced pre-trained models from transformers library by Hugging Face, for your sentiment analysis model.

2. **Chatbot:** Design a chatbot serving a specific purpose such as customer service for a certain industry, a personal fitness coach, or a study helper. Libraries like ChatterBot or Dialogflow can assist in designing conversational agents.

3. **Predictive Text Application:** Develop a model that suggests the next word or sentence similar to predictive text on smartphone keyboards. You could use the transformers library by Hugging Face, which includes pre-trained models like GPT-2.

4. **Image Classification Application:** Create a model to distinguish between different types of flowers or fruits. For this type of image classification task, pre-trained models like ResNet or VGG from PyTorch or TensorFlow can be utilized.

5. **News Article Classifier:** Develop a text classification model that categorizes news articles into predefined categories. NLTK, SpaCy, and sklearn are valuable libraries for text pre-processing, feature extraction, and building classification models.

6. **Recommendation System:** Create a simplified recommendation system. For instance, a book or movie recommender based on user preferences. Python's Surprise library can assist in building effective recommendation systems.

7. **Plant Disease Detection:** Develop a model to identify diseases in plants using leaf images. This project requires a good understanding of convolutional neural networks (CNNs) and image processing. PyTorch, TensorFlow, and OpenCV are all great tools to use.

8. **Facial Expression Recognition:** Develop a model to classify human facial expressions. This involves complex feature extraction and classification algorithms. You might want to leverage deep learning libraries like TensorFlow or PyTorch, along with OpenCV for processing facial images.

9. **Chest X-Ray Interpretation:** Develop a model to detect abnormalities in chest X-ray images. This task may require understanding of specific features in such images. Again, TensorFlow and PyTorch for deep learning, and libraries like SciKit-Image or PIL for image processing, could be of use.

10. **Food Classification:** Develop a model to classify a variety of foods such as local Indonesian food. Pre-trained models like ResNet or VGG from PyTorch or TensorFlow can be a good starting point.

11. **Traffic Sign Recognition:** Design a model to recognize different traffic signs. This project has real-world applicability in self-driving car technology. Once more, you might utilize PyTorch or TensorFlow for the deep learning aspect, and OpenCV for image processing tasks.

**Submission:**

Please upload both your model and application to Huggingface or your own Github account for submission.

**Presentation:**

You are required to create a presentation to showcase your project, including the following details:

- The objective of your model.
- A comprehensive description of your model.
- The specific metrics used to measure your model's effectiveness.
- A brief overview of the dataset used, including its source, pre-processing steps, and any insights.
- An explanation of the methodology used in developing the model.
- A discussion on challenges faced, how they were handled, and your learnings from those.
- Suggestions for potential future improvements to the model.
- A functioning link to a demo of your model in action.

**Grading:**

Submissions will be manually graded, with a select few given the opportunity to present their projects in front of a panel of judges. This will provide valuable feedback, further enhancing your project and expanding your knowledge base.

Remember, consistent practice is the key to mastering these concepts. Apply your knowledge, ask questions when in doubt, and above all, enjoy the process. Best of luck to you all!


In [ ]:
# @title #### Student Identity
student_id = "REAJGDG4" # @param {type:"string"}
name = "Hamzah Arman Husni" # @param {type:"string"}
drive_link = "https://colab.research.google.com/drive/1XiJGQQLIAlSiHT_AN2cg-sA47GOHW84d?authuser=1"  # @param {type:"string"}
assignment_id = "00_portfolio_project"

## Installation and Import `rggrader` Package

In [ ]:
%pip install rggrader
from rggrader import submit_image
from rggrader import submit

## Working Space

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.15.0


In [ ]:
!pip3 install --quiet tensorflow-text

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 58.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.8/589.8 MB 2.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 100.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 73.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 114.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 69.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 286.8/286.8 kB 33.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tf-keras 2.15.1 requires tensorflow<2.16,>=2.15, but you have tensorflow 2.16.1 which is incompatible.


In [ ]:
# Check for GPU
!nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-52a7ec50-a58d-135a-c56b-382b4feff26e)


In [ ]:
!git clone https://github.com/Franck-Dernoncourt/pubmed-rct.git
!ls pubmed-rct

Cloning into 'pubmed-rct'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 39 (delta 8), reused 5 (delta 5), pack-reused 25
Receiving objects: 100% (39/39), 177.08 MiB | 15.39 MiB/s, done.
Resolving deltas: 100% (15/15), done.
Updating files: 100% (13/13), done.
PubMed_200k_RCT				       PubMed_20k_RCT_numbers_replaced_with_at_sign
PubMed_200k_RCT_numbers_replaced_with_at_sign  README.md
PubMed_20k_RCT


# Get The Data

The authors of the paper have generously made the data they utilized for their research publicly accessible and free of charge, providing it in the form of .txt files on GitHub.

We can copy them to our local directory using git clone https://github.com/Franck-Dernoncourt/pubmed-rct.

In [ ]:
# Check what files are in the PubMed_20K dataset
!ls pubmed-rct/PubMed_20k_RCT_numbers_replaced_with_at_sign

dev.txt  test.txt  train.txt


In [ ]:
# Start by using the 20k dataset
data_dir = "pubmed-rct/PubMed_20k_RCT_numbers_replaced_with_at_sign/"

In [ ]:
# Check all of the filenames in the target directory
import os
filenames = [data_dir + filename for filename in os.listdir(data_dir)]
filenames

['pubmed-rct/PubMed_20k_RCT_numbers_replaced_with_at_sign/test.txt',
 'pubmed-rct/PubMed_20k_RCT_numbers_replaced_with_at_sign/dev.txt',
 'pubmed-rct/PubMed_20k_RCT_numbers_replaced_with_at_sign/train.txt']

In [ ]:
# pengolahan data dengan 200k dataset

# import zipfile

# zip_file_path = "pubmed-rct/PubMed_200k_RCT_numbers_replaced_with_at_sign/train.zip"
# extract_to_directory = "pubmed-rct/PubMed_200k_RCT_numbers_replaced_with_at_sign/"

# # Open the zip file
# with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
#     # Extract all the contents into the specified directory
#     zip_ref.extractall(extract_to_directory)

# print("Extraction completed successfully.")

# Preprocess Data

In [ ]:
# Check the text
with open(data_dir + "train.txt", "r") as f:
    train_lines = f.readlines()

train_lines[:50]

['###24293578\n',
 'OBJECTIVE\tTo investigate the efficacy of @ weeks of daily low-dose oral prednisolone in improving pain , mobility , and systemic low-grade inflammation in the short term and whether the effect would be sustained at @ weeks in older adults with moderate to severe knee osteoarthritis ( OA ) .\n',
 'METHODS\tA total of @ patients with primary knee OA were randomized @:@ ; @ received @ mg/day of prednisolone and @ received placebo for @ weeks .\n',
 'METHODS\tOutcome measures included pain reduction and improvement in function scores and systemic inflammation markers .\n',
 'METHODS\tPain was assessed using the visual analog pain scale ( @-@ mm ) .\n',
 'METHODS\tSecondary outcome measures included the Western Ontario and McMaster Universities Osteoarthritis Index scores , patient global assessment ( PGA ) of the severity of knee OA , and @-min walk distance ( @MWD ) .\n',
 'METHODS\tSerum levels of interleukin @ ( IL-@ ) , IL-@ , tumor necrosis factor ( TNF ) - , and 

In [ ]:
# Create function to read the lines of a document
def get_lines(filename):
  with open(filename, "r") as f:
    return f.readlines()

In [ ]:
def preprocess_text_with_line_numbers(filename):
  input_lines = get_lines(filename) # get all lines from filename
  abstract_lines = "" # create an empty abstract
  abstract_samples = [] # create an empty list of abstracts

  # Loop through each line in target file
  for line in input_lines:
    if line.startswith("###"): # check to see if line is an ID line
      abstract_id = line
      abstract_lines = "" # reset abstract string
    elif line.isspace(): # check to see if line is a new line
      abstract_line_split = abstract_lines.splitlines() # split abstract into separate lines

      # Iterate through each line in abstract and count them at the same time
      for abstract_line_number, abstract_line in enumerate(abstract_line_split):
        line_data = {} # create empty dict to store data from line
        target_text_split = abstract_line.split("\t") # split target label from text
        line_data["target"] = target_text_split[0] # get target label
        line_data["text"] = target_text_split[1].lower() # get target text and lower it
        line_data["line_number"] = abstract_line_number # what number line does the line appear in the abstract?
        line_data["total_lines"] = len(abstract_line_split) - 1 # how many total lines are in the abstract? (start from 0)
        abstract_samples.append(line_data) # add line data to abstract samples list

    else: # if the above conditions aren't fulfilled, the line contains a labelled sentence
      abstract_lines += line

  return abstract_samples

In [ ]:
# Get data from file and preprocess it

train_samples = preprocess_text_with_line_numbers(data_dir + "train.txt")
val_samples = preprocess_text_with_line_numbers(data_dir + "dev.txt") # dev is another name for validation set
test_samples = preprocess_text_with_line_numbers(data_dir + "test.txt")
len(train_samples), len(val_samples), len(test_samples)

(180040, 30212, 30135)

In [ ]:
# Check the first abstract of our training data
train_samples[:15]

[{'target': 'OBJECTIVE',
  'text': 'to investigate the efficacy of @ weeks of daily low-dose oral prednisolone in improving pain , mobility , and systemic low-grade inflammation in the short term and whether the effect would be sustained at @ weeks in older adults with moderate to severe knee osteoarthritis ( oa ) .',
  'line_number': 0,
  'total_lines': 11},
 {'target': 'METHODS',
  'text': 'a total of @ patients with primary knee oa were randomized @:@ ; @ received @ mg/day of prednisolone and @ received placebo for @ weeks .',
  'line_number': 1,
  'total_lines': 11},
 {'target': 'METHODS',
  'text': 'outcome measures included pain reduction and improvement in function scores and systemic inflammation markers .',
  'line_number': 2,
  'total_lines': 11},
 {'target': 'METHODS',
  'text': 'pain was assessed using the visual analog pain scale ( @-@ mm ) .',
  'line_number': 3,
  'total_lines': 11},
 {'target': 'METHODS',
  'text': 'secondary outcome measures included the western ontari

In [ ]:
import pandas as pd
train_df = pd.DataFrame(train_samples)
val_df = pd.DataFrame(val_samples)
test_df = pd.DataFrame(test_samples)
train_df.head(15)

target                                               text  \
0     OBJECTIVE  to investigate the efficacy of @ weeks of dail...   
1       METHODS  a total of @ patients with primary knee oa wer...   
2       METHODS  outcome measures included pain reduction and i...   
3       METHODS  pain was assessed using the visual analog pain...   
4       METHODS  secondary outcome measures included the wester...   
5       METHODS  serum levels of interleukin @ ( il-@ ) , il-@ ...   
6       RESULTS  there was a clinically relevant reduction in t...   
7       RESULTS  the mean difference between treatment arms ( @...   
8       RESULTS  further , there was a clinically relevant redu...   
9       RESULTS  these differences remained significant at @ we...   
10      RESULTS  the outcome measures in rheumatology clinical ...   
11  CONCLUSIONS  low-dose oral prednisolone had both a short-te...   
12   BACKGROUND  emotional eating is associated with overeating...   
13   BACKGROUND  yet , empirical evidence for individual ( trai...   
14    OBJECTIVE  the aim of this study was to test if attention...   

    line_number  total_lines  
0             0           11  
1             1           11  
2             2           11  
3             3           11  
4             4           11  
5             5           11  
6             6           11  
7             7           11  
8             8           11  
9             9           11  
10           10           11  
11           11           11  
12            0           10  
13            1           10  
14            2           10

In [ ]:
# Distribution of labels in training data
train_df.target.value_counts()

METHODS        59353
RESULTS        57953
CONCLUSIONS    27168
BACKGROUND     21727
OBJECTIVE      13839
Name: target, dtype: int64

# Preprocess

In [ ]:
import nltk
from nltk.corpus import stopwords
import re

nltk.download("stopwords")
STOPWORDS = stopwords.words("english")
print (STOPWORDS[:5])

def preprocess(text, stopwords=STOPWORDS):
    """Conditional preprocessing on our text unique to our task."""
    # Lower
    text = text.lower()

    # Remove stopwords
    pattern = re.compile(r"\b(" + r"|".join(stopwords) + r")\b\s*")
    text = pattern.sub("", text)

    # Remove words in paranthesis
    text = re.sub(r"\([^)]*\)", "", text)

    # Spacing and filters
    text = re.sub(r"([-;;.,!?<=>])", r" \1 ", text)
    text = re.sub("[^A-Za-z0-9]+", " ", text) # remove non alphanumeric chars
    text = re.sub(" +", " ", text)  # remove multiple spaces
    text = text.strip()

    return text


# Apply to dataframe
preprocessed_train_df = train_df.copy()
preprocessed_train_df.text = preprocessed_train_df.text.apply(preprocess)
print (f"{train_df.text.values[0]}\n\n{preprocessed_train_df.text.values[0]}")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


['i', 'me', 'my', 'myself', 'we']
to investigate the efficacy of @ weeks of daily low-dose oral prednisolone in improving pain , mobility , and systemic low-grade inflammation in the short term and whether the effect would be sustained at @ weeks in older adults with moderate to severe knee osteoarthritis ( oa ) .

investigate efficacy weeks daily low dose oral prednisolone improving pain mobility systemic low grade inflammation short term whether effect would sustained weeks older adults moderate severe knee osteoarthritis


In [ ]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet as wn

# Initialize WordNetLemmatizer outside the function for efficiency
lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    # Map POS tags from Penn Treebank POS tags to WordNet POS tags
    def get_wordnet_pos(tag):
        if tag.startswith('J'):
            return wn.ADJ
        elif tag.startswith('V'):
            return wn.VERB
        elif tag.startswith('N'):
            return wn.NOUN
        elif tag.startswith('R'):
            return wn.ADV
        else:
            return wn.NOUN  # Default to noun if no match

    # Tokenize text and get POS tags
    tokens = nltk.word_tokenize(text)
    pos_tags = nltk.pos_tag(tokens)

    # Lemmatize tokens using WordNetLemmatizer with appropriate POS tags
    lemmatized_tokens = [lemmatizer.lemmatize(word, get_wordnet_pos(pos_tag)) for word, pos_tag in pos_tags]

    # Join lemmatized tokens back into a single string
    return ' '.join(lemmatized_tokens)

# Apply lemmatization function to 'text' column of preprocessed_df
preprocessed_train_df['text'] = preprocessed_train_df['text'].apply(lemmatize_text)


In [ ]:
preprocessed_train_df.head(20)

target                                               text  \
0     OBJECTIVE  investigate efficacy week daily low dose oral ...   
1       METHODS  total patient primary knee oa randomize receiv...   
2       METHODS  outcome measure include pain reduction improve...   
3       METHODS           pain assess use visual analog pain scale   
4       METHODS  secondary outcome measure include western onta...   
5       METHODS  serum level interleukin il tumor necrosis fact...   
6       RESULTS  clinically relevant reduction intervention gro...   
7       RESULTS  mean difference treatment arm p p p p respecti...   
8       RESULTS  clinically relevant reduction serum level il i...   
9       RESULTS                 difference remain significant week   
10      RESULTS  outcome measure rheumatology clinical trial os...   
11  CONCLUSIONS  low dose oral prednisolone short term longer s...   
12   BACKGROUND  emotional eating associate overeat development...   
13   BACKGROUND  yet empirical evidence individual difference e...   
14    OBJECTIVE  aim study test attention bias food moderate ef...   
15    OBJECTIVE  expect emotional eating predictive elevate att...   
16      METHODS  participant randomly assign one two experiment...   
17      METHODS  attentional bias high caloric food measure eye...   
18      METHODS  self report emotional eating assess dutch eati...   
19      RESULTS  hierarchical multivariate regression modeling ...   

    line_number  total_lines  
0             0           11  
1             1           11  
2             2           11  
3             3           11  
4             4           11  
5             5           11  
6             6           11  
7             7           11  
8             8           11  
9             9           11  
10           10           11  
11           11           11  
12            0           10  
13            1           10  
14            2           10  
15            3           10  
16            4           10  
17            5           10  
18            6           10  
19            7           10

# One Hot Encode

In [ ]:
# data category one-hot-encoding
target = pd.get_dummies(preprocessed_train_df.target)
df_target = pd.concat([preprocessed_train_df, target], axis=1)
df_target = df_target.drop(columns='target')
df_target.drop(columns=['line_number', 'total_lines'], inplace=True)
df_target.head(10)

text  BACKGROUND  CONCLUSIONS  \
0  investigate efficacy week daily low dose oral ...           0            0   
1  total patient primary knee oa randomize receiv...           0            0   
2  outcome measure include pain reduction improve...           0            0   
3           pain assess use visual analog pain scale           0            0   
4  secondary outcome measure include western onta...           0            0   
5  serum level interleukin il tumor necrosis fact...           0            0   
6  clinically relevant reduction intervention gro...           0            0   
7  mean difference treatment arm p p p p respecti...           0            0   
8  clinically relevant reduction serum level il i...           0            0   
9                 difference remain significant week           0            0   

   METHODS  OBJECTIVE  RESULTS  
0        0          1        0  
1        1          0        0  
2        1          0        0  
3        1          0        0  
4        1          0        0  
5        1          0        0  
6        0          0        1  
7        0          0        1  
8        0          0        1  
9        0          0        1

In [ ]:
# change dataframe value to numpy array
text = df_target['text'].values
train_labels_one_hot = df_target[['BACKGROUND', 'CONCLUSIONS', 'METHODS', 'OBJECTIVE', 'RESULTS']].values
train_labels_one_hot


array([[0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       ...,
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0]], dtype=uint8)

# Validation and Test One Hot Code


In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Create an instance of OneHotEncoder
one_hot_encoder = OneHotEncoder(sparse=False)

# Fit the OneHotEncoder to the training labels
train_labels_one_hot = one_hot_encoder.fit_transform(train_df['target'].to_numpy().reshape(-1, 1))
# Transform the validation and test labels using the fitted OneHotEncoder
val_labels_one_hot = one_hot_encoder.transform(val_df['target'].to_numpy().reshape(-1, 1))
test_labels_one_hot = one_hot_encoder.transform(test_df['target'].to_numpy().reshape(-1, 1))

# Now you can use the transformed labels
print(train_labels_one_hot)
print(val_labels_one_hot)
print(test_labels_one_hot)


[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


# Label Encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

train_label_encoded = label_encoder.fit_transform(train_df['target'].to_numpy())
val_label_encoded = label_encoder.transform(val_df['target'].to_numpy())
test_label_encoded = label_encoder.transform(test_df['target'].to_numpy())

train_label_encoded

array([3, 2, 2, ..., 4, 1, 1])

In [ ]:
num_classes = len(label_encoder.classes_)
class_names = label_encoder.classes_

num_classes, class_names

(5,
 array(['BACKGROUND', 'CONCLUSIONS', 'METHODS', 'OBJECTIVE', 'RESULTS'],
       dtype=object))

In [ ]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_result(y_true, y_pred):
  accuracy = accuracy_score(y_true, y_pred)
  model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, average='weighted')
  model_results = {
      'accurecy': accuracy,
      'precision': model_precision,
      'recall': model_recall,
      'f1-score': model_f1,
  }

  return model_results

the PubMed 200k RCT paper states the vocabulary size of the PubMed 20k dataset as 68,000. So we'll use that as our max_tokens parameter.

In [ ]:
train_sentences = preprocessed_train_df['text'].tolist()
val_sentences = val_df['text'].tolist()
test_sentences = test_df['text'].tolist()

len(train_sentences), len(val_sentences), len(test_sentences)

(180040, 30212, 30135)

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization, Embedding


max_vocab_length = 68000
max_length = 55

text_vectorizer = TextVectorization(
    max_tokens=max_vocab_length,
    output_mode='int',
    output_sequence_length=max_length,
)

In [ ]:
max_vocab_length = 68000
max_length = 55

text_vectorizer = TextVectorization(
    max_tokens=max_vocab_length,
    output_mode='int',
    output_sequence_length=max_length,
)

text_vectorizer.adapt(train_sentences)

# How many words in our training vocabulary?
rct_20k_text_vocab = text_vectorizer.get_vocabulary()
print(f"Number of words in vocabulary: {len(rct_20k_text_vocab)}"),
print(f"Most common words in the vocabulary: {rct_20k_text_vocab[:5]}")
print(f"Least common words in the vocabulary: {rct_20k_text_vocab[-5:]}")

Cause: Unable to locate the source code of <function PreprocessingLayer.make_adapt_function.<locals>.adapt_step at 0x7ee373b3b130>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Cause: Unable to locate the source code of <function PreprocessingLayer.make_adapt_function.<locals>.adapt_step at 0x7ee373b3b130>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Number of words in vocabulary: 39204
Most common words in the vocabulary: ['', '[UNK]', 'group', 'patient', 'study']
Least common words in the vocabulary: ['aap', 'aae', 'aado', 'aachener', 'aachen']


In [ ]:
embedding = Embedding(
    input_dim = len(rct_20k_text_vocab),
    output_dim = 128,
    name='token_embedding'

)

# List of Sentence

# Dataset

In [ ]:
import tensorflow as tf

# Turn our data into TensorFlow Datasets
train_dataset = tf.data.Dataset.from_tensor_slices((train_sentences, train_labels_one_hot))
valid_dataset = tf.data.Dataset.from_tensor_slices((val_sentences, val_labels_one_hot))
test_dataset = tf.data.Dataset.from_tensor_slices((test_sentences, test_labels_one_hot))

train_dataset

<_TensorSliceDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(5,), dtype=tf.float64, name=None))>

In [ ]:
# Take the TensorSliceDataset's and turn them into prefetched batches
train_dataset = train_dataset.batch(32).prefetch(tf.data.AUTOTUNE)
valid_dataset = valid_dataset.batch(32).prefetch(tf.data.AUTOTUNE)
test_dataset = test_dataset.batch(32).prefetch(tf.data.AUTOTUNE)

train_dataset

<_PrefetchDataset element_spec=(TensorSpec(shape=(None,), dtype=tf.string, name=None), TensorSpec(shape=(None, 5), dtype=tf.float64, name=None))>

# Preparing our data for deep learning models

In [ ]:
import tensorflow_hub as hub
import tensorflow as tf
from tensorflow.keras import layers

# Download pretrained TensorFlow Hub USE
import tensorflow_hub as hub
tf_hub_embedding_layer = hub.KerasLayer("https://tfhub.dev/google/universal-sentence-encoder/4",
                                        trainable=False,
                                        name="universal_sentence_encoder")
# Define feature extractor model using TF Hub layer
inputs = layers.Input(shape=[], dtype=tf.string)
pretrained_embedding = tf_hub_embedding_layer(inputs) # tokenize text and create embedding
x = layers.Dense(512, activation="relu")(pretrained_embedding) # add a fully connected layer on top of the embedding
x = layers.Dense(256, activation = "relu")(x)
x  = layers.Dense(128, activation = "relu")(x)
# Note: you could add more layers here if you wanted to
outputs = layers.Dense(5, activation="softmax")(x) # create the output layer
model = tf.keras.Model(inputs=inputs,
                        outputs=outputs)

# Compile the model
model.compile(loss="categorical_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])
# Get a summary of the model
model.summary()


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None,)]                 0         
                                                                 
 universal_sentence_encoder  (None, 512)               256797824 
  (KerasLayer)                                                   
                                                                 
 dense (Dense)               (None, 512)               262656    
                                                                 
 dense_1 (Dense)             (None, 256)               131328    
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 5)                 645       
                                                             

In [ ]:
# Define a learning rate reduction callback
reduce_lr_callback = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',  # Monitor validation loss
    factor=0.2,           # Factor by which the learning rate will be reduced
    patience=3,           # Number of epochs with no improvement after which learning rate will be reduced
    min_lr=0.000003,        # Lower bound on the learning rate
    verbose=1             # Print a message if the learning rate is reduced
)

# Define early stopping callback
early_stopping_callback = tf.keras.callbacks.EarlyStopping(
    monitor = 'val_loss',  # Monitor validation loss
    patience=5,         # Number of epochs with no improvement after which training will be stopped
    restore_best_weights=True  # Restore model weights to the epoch with the best validation loss
)

In [ ]:
# Train the model with both callbacks
history = model.fit(train_dataset, epochs=20,
                    validation_data=valid_dataset,
                    verbose=1,
                    callbacks=[reduce_lr_callback, early_stopping_callback])

Epoch 1/20
5627/5627 [==============================] - 96s 15ms/step - loss: 0.8597 - accuracy: 0.6675 - val_loss: 0.8277 - val_accuracy: 0.6762 - lr: 0.0010
Epoch 2/20
5627/5627 [==============================] - 83s 15ms/step - loss: 0.7559 - accuracy: 0.7104 - val_loss: 0.8560 - val_accuracy: 0.6738 - lr: 0.0010
Epoch 3/20
5627/5627 [==============================] - 76s 14ms/step - loss: 0.6892 - accuracy: 0.7380 - val_loss: 0.8812 - val_accuracy: 0.6765 - lr: 0.0010
Epoch 4/20
5627/5627 [==============================] - ETA: 0s - loss: 0.6262 - accuracy: 0.7632
Epoch 4: ReduceLROnPlateau reducing learning rate to 0.00020000000949949026.
5627/5627 [==============================] - 104s 18ms/step - loss: 0.6262 - accuracy: 0.7632 - val_loss: 0.9630 - val_accuracy: 0.6692 - lr: 0.0010
Epoch 5/20
5627/5627 [==============================] - 88s 16ms/step - loss: 0.5139 - accuracy: 0.8054 - val_loss: 1.0729 - val_accuracy: 0.6789 - lr: 2.0000e-04
Epoch 6/20
5627/5627 [==============

# Save Model

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Link download model : https://drive.google.com/drive/folders/1nd87k60AtMgh_jBBPXxm3ELNER2PjUV4?usp=drive_link

In [ ]:
model.save('Skimlit_UniversalModel')

In [ ]:
import shutil

# Define the source and destination paths
source_folder = "/content/'Skimlit_UniversalModel"
destination_folder = "'/content/drive/MyDrive/Colab Notebooks/Final Project Skill Academy/Skimlit_UniversalModel'"

# Copy the folder recursively
shutil.copytree(source_folder, destination_folder)


'/content/drive/My Drive/destination_folder'

In [2]:
import tensorflow as tf
# loaded_model = tf.keras.models.load_model('/content/Skimlit_UniversalModel')
loaded_model = tf.keras.models.load_model('/content/drive/MyDrive/Colab Notebooks/Final Project Skill Academy/Skimlit_UniversalModel')

In [4]:
import tensorflow as tf
# Load your trained model
model = tf.keras.models.load_model("/content/drive/MyDrive/Colab Notebooks/Final Project Skill Academy/Skimlit_UniversalModel")

# Save the model to H5 format
model.save('model.hdf5')

print("Model successfully saved in hdf5 format!")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


Model successfully saved in hdf5 format!


# Make Example Prediction

In [11]:
classes = ['BACKGROUND', 'CONCLUSIONS', 'METHODS', 'OBJECTIVE', 'RESULTS']

In [5]:

abstract = '''The problems lies not in spite of the sanitary residence neighborhood into a place or source of
sanitation issues. The sanitation problems as the density of larvae that are in the environment around the
house. The aim of this study was to analyze association between housing sanitation with the axistence of
Aedes sp. larvae in working area of Public Health Center of Kutaraya, Kayu Agung. This study used a cross-sectional design, this study population was a entire house or building which
is located in Public Health Center of Kutaraya. The sample amounted to 101 homes and buildings
calculated with formula hypothesis test two proportions. Sampling by cluster random sampling technique.
The collecting data used questionnaires and checklist. Data analysis was univariate, bivariate analysis using
chi square test and Fisher Exact. Data analysis was perfomend by bivariate was a correlation between the presence of second-hand
goods with larvae density ρ-value (0.001), the presence of water tanks/containers with larvae density by ρ
value (0.000) and there was a correlation between the presence of clothing hanging at a density larvae Aedes
sp. with ρ-value (0.002). DF value at level 6 and 7, HI 43% and BI 72%. Variables related to the density of larvae Aedes sp. namely the existence of thrift, the presence
of water tanks/containers and the existence of clothes hanging. We recommend  to research include keeping
and attention environmental sanitation in order to avoid transmitting dengue mosquito breeding sites so as to
reduce the number population mosquitoes.'''
# Create sentencizer - Source: https://spacy.io/usage/linguistic-features#sbd
from spacy.lang.en import English
nlp = English() # setup English sentence parser

# New version of spaCy
sentencizer = nlp.add_pipe("sentencizer") # create sentence splitting pipeline object

# Old version of spaCy
# sentencizer = nlp.create_pipe("sentencizer") # create sentence splitting pipeline object
# nlp.add_pipe(sentencizer) # add sentence splitting pipeline object to sentence parser

# Create "doc" of parsed sequences, change index for a different abstract
doc = nlp(abstract)
abstract_lines = [str(sent) for sent in list(doc.sents)] # return detected sentences from doc in string type (not spaCy token type)
abstract_lines

['The problems lies not in spite of the sanitary residence neighborhood into a place or source of\nsanitation issues.',
 'The sanitation problems as the density of larvae that are in the environment around the\nhouse.',
 'The aim of this study was to analyze association between housing sanitation with the axistence of\nAedes sp.',
 'larvae in working area of Public Health Center of Kutaraya, Kayu Agung.',
 'This study used a cross-sectional design, this study population was a entire house or building which\nis located in Public Health Center of Kutaraya.',
 'The sample amounted to 101 homes and buildings\ncalculated with formula hypothesis test two proportions.',
 'Sampling by cluster random sampling technique.',
 '\nThe collecting data used questionnaires and checklist.',
 'Data analysis was univariate, bivariate analysis using\nchi square test and Fisher Exact.',
 'Data analysis was perfomend by bivariate was a correlation between the presence of second-hand\ngoods with larvae densit

In [6]:
# Get total number of lines
total_lines_in_sample = len(abstract_lines)

# Go through each line in abstract and create a list of dictionaries containing features for each line
sample_lines = []
for i, line in enumerate(abstract_lines):
  sample_dict = {}
  sample_dict["text"] = str(line)
  sample_dict["line_number"] = i
  sample_dict["total_lines"] = total_lines_in_sample - 1
  sample_lines.append(sample_dict)
sample_lines

[{'text': 'The problems lies not in spite of the sanitary residence neighborhood into a place or source of\nsanitation issues.',
  'line_number': 0,
  'total_lines': 14},
 {'text': 'The sanitation problems as the density of larvae that are in the environment around the\nhouse.',
  'line_number': 1,
  'total_lines': 14},
 {'text': 'The aim of this study was to analyze association between housing sanitation with the axistence of\nAedes sp.',
  'line_number': 2,
  'total_lines': 14},
 {'text': 'larvae in working area of Public Health Center of Kutaraya, Kayu Agung.',
  'line_number': 3,
  'total_lines': 14},
 {'text': 'This study used a cross-sectional design, this study population was a entire house or building which\nis located in Public Health Center of Kutaraya.',
  'line_number': 4,
  'total_lines': 14},
 {'text': 'The sample amounted to 101 homes and buildings\ncalculated with formula hypothesis test two proportions.',
  'line_number': 5,
  'total_lines': 14},
 {'text': 'Sampling by

In [7]:
# Make predictions on sample abstract features
test_abstract_pred_probs = loaded_model.predict(x=( tf.constant(abstract_lines)))
test_abstract_pred_probs

1/1 [==============================] - 1s 1s/step


array([[5.31091690e-01, 1.08065039e-01, 5.94599508e-02, 1.25185579e-01,
        1.76197708e-01],
       [6.50381625e-01, 9.06736627e-02, 3.21984589e-02, 1.10513017e-01,
        1.16233259e-01],
       [3.43630910e-01, 3.86127383e-02, 2.07298175e-01, 3.68789405e-01,
        4.16687727e-02],
       [2.25890175e-01, 8.20162743e-02, 4.50805873e-01, 3.82897481e-02,
        2.02997774e-01],
       [4.69326600e-02, 2.53472254e-02, 8.18877757e-01, 1.63396131e-02,
        9.25027430e-02],
       [2.31659054e-04, 5.64265298e-04, 9.33862507e-01, 2.87126109e-04,
        6.50543496e-02],
       [4.78386573e-05, 9.06176429e-05, 9.85402048e-01, 5.52145539e-05,
        1.44041553e-02],
       [2.73604353e-04, 7.89928483e-04, 9.90450382e-01, 2.22670540e-04,
        8.26325081e-03],
       [4.06157720e-04, 7.78236252e-04, 8.65751624e-01, 3.30014358e-04,
        1.32733911e-01],
       [1.27563113e-02, 5.02584986e-02, 5.32784872e-02, 5.66754118e-03,
        8.78039181e-01],
       [1.19071640e-01, 1.9546

In [8]:
# Turn prediction probabilities into prediction classes
test_abstract_preds = tf.argmax(test_abstract_pred_probs, axis=1)
test_abstract_preds

<tf.Tensor: shape=(15,), dtype=int64, numpy=array([0, 0, 3, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 1])>

In [12]:
# Turn prediction class integers into string class names
test_abstract_pred_classes = [classes[i] for i in test_abstract_preds]
test_abstract_pred_classes

['BACKGROUND',
 'BACKGROUND',
 'OBJECTIVE',
 'METHODS',
 'METHODS',
 'METHODS',
 'METHODS',
 'METHODS',
 'METHODS',
 'RESULTS',
 'RESULTS',
 'RESULTS',
 'RESULTS',
 'RESULTS',
 'CONCLUSIONS']

In [13]:
# Visualize abstract lines and predicted sequence labels
for i, line in enumerate(abstract_lines):
  print(f"{test_abstract_pred_classes[i]}: {line}")

BACKGROUND: The problems lies not in spite of the sanitary residence neighborhood into a place or source of
sanitation issues.
BACKGROUND: The sanitation problems as the density of larvae that are in the environment around the
house.
OBJECTIVE: The aim of this study was to analyze association between housing sanitation with the axistence of
Aedes sp.
METHODS: larvae in working area of Public Health Center of Kutaraya, Kayu Agung.
METHODS: This study used a cross-sectional design, this study population was a entire house or building which
is located in Public Health Center of Kutaraya.
METHODS: The sample amounted to 101 homes and buildings
calculated with formula hypothesis test two proportions.
METHODS: Sampling by cluster random sampling technique.
METHODS: 
The collecting data used questionnaires and checklist.
METHODS: Data analysis was univariate, bivariate analysis using
chi square test and Fisher Exact.
RESULTS: Data analysis was perfomend by bivariate was a correlation between 

In [15]:
!pip install gradio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 20.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.1/92.1 kB 11.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 29.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 8.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.5/138.5 kB 15.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 48.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 6.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.9/129.9 kB 14.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 kB 9.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 5.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.5/71.5 kB 8.6 MB/s eta 0:00:00
  Created wheel for ffmpy: filename=ffmpy-0.3.2-py3-none-any.whl size

In [16]:
import gradio as gr
from spacy.lang.en import English
import tensorflow as tf

# Load your pre-trained model

# Define a function to process input text and make predictions
def predict_abstract(abstract):
    classes = ['BACKGROUND', 'CONCLUSIONS', 'METHODS', 'OBJECTIVE', 'RESULTS']
    nlp = English()
    sentencizer = nlp.add_pipe("sentencizer") # create sentence splitting pipeline object
    doc = nlp(abstract)
    abstract_lines = [str(sent) for sent in list(doc.sents)]
    total_lines_in_sample = len(abstract_lines)
    sample_lines = []
    for i, line in enumerate(abstract_lines):
        sample_dict = {}
        sample_dict["text"] = str(line)
        sample_dict["line_number"] = i
        sample_dict["total_lines"] = total_lines_in_sample - 1
        sample_lines.append(sample_dict)
    test_abstract_pred_probs = loaded_model.predict(x=( tf.constant(abstract_lines)))
    test_abstract_preds = tf.argmax(test_abstract_pred_probs, axis=1)
    test_abstract_preds = tf.argmax(test_abstract_pred_probs, axis=1)
    test_abstract_pred_classes = [classes[i] for i in test_abstract_preds]
    # Combine predicted classes with abstract lines
    results = ""
    for class_name, line in zip(test_abstract_pred_classes, abstract_lines):
        results += f"{class_name}: {line}\n"
    return results


# Create Gradio interface
input_text = gr.Textbox(label="Input Abstract")
output_text = gr.Textbox(label="Predicted Label")

gr.Interface(fn=predict_abstract, inputs=input_text, outputs=output_text, title="Abstract Classifier").launch()



Setting queue=True in a Colab notebook requires sharing enabled. Setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://d2e9ef9808579eefec.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


In [ ]:
portfolio_link = "https://drive.google.com/drive/folders/1SivWOzuU9L3pf7iLjeCxVr7-of27w0IN?usp=sharing"
presentation_link = "https://drive.google.com/drive/folders/1K-2JsOY8mpfyh3XLCappJTB8T5cako14?usp=sharing"

question_id = "01_portfolio_link"
submit(student_id, name, assignment_id, str(portfolio_link), question_id, drive_link)

question_id = "02_presentation_link"
submit(student_id, name, assignment_id, str(presentation_link), question_id, drive_link)

'Assignment successfully submitted'